/*
 * gen_offsets.c
 * * Compiles with MatanelOS headers to generate NASM-compatible
 * definitions for struct offsets, sizes, and enums.
 */

#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#include "includes/annotations.h"
#include "includes/ms.h"
#include "includes/mm.h"
#include "includes/ps.h"
#include "includes/me.h" 

// --------------------------------------------------------------------------
// MACROS FOR GENERATION
// --------------------------------------------------------------------------

#define GEN_COMMENT(msg) \
    printf("\n; %s\n", msg)

#define GEN_DEFINE(name, val) \
    printf("%%define %-40s 0x%lX\n", #name, (uint64_t)(val))

#define GEN_OFFSET(struct_name, member) \
    printf("%%define %-40s 0x%lX\n", #struct_name "_" #member, offsetof(struct_name, member))

#define GEN_SIZE(struct_name) \
    printf("%%define SIZEOF_%-33s 0x%lX\n", #struct_name, sizeof(struct_name))

int main(void) {
    printf("; ===============================================================\n");
    printf("; AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY\n");
    printf("; Generated by gen_offsets.c\n");
    printf("; ===============================================================\n\n");

    // GENERALS
    GEN_DEFINE(NULL, 0);

    // ========================================================================
    // 1. EXECUTIVE / PROCESSOR (me.h)
    // ========================================================================
    GEN_COMMENT("PROCESSOR Structure Offsets (gs:[...])");
    GEN_OFFSET(PROCESSOR, self);
    GEN_OFFSET(PROCESSOR, currentIrql);
    GEN_OFFSET(PROCESSOR, schedulerEnabled);
    GEN_OFFSET(PROCESSOR, currentThread);
    GEN_OFFSET(PROCESSOR, readyQueue);
    GEN_OFFSET(PROCESSOR, ID);
    GEN_OFFSET(PROCESSOR, lapic_ID);
    GEN_OFFSET(PROCESSOR, VirtStackTop);
    GEN_OFFSET(PROCESSOR, tss);
    GEN_OFFSET(PROCESSOR, flags);
    GEN_OFFSET(PROCESSOR, schedulePending);
    GEN_OFFSET(PROCESSOR, LapicAddressVirt);
    GEN_OFFSET(PROCESSOR, TimerExpirationDPC);
    GEN_SIZE(PROCESSOR);

    GEN_COMMENT("TRAP_FRAME Offsets (Context Saving/Restoring)");
    GEN_OFFSET(TRAP_FRAME, rax);
    GEN_OFFSET(TRAP_FRAME, rbx);
    GEN_OFFSET(TRAP_FRAME, rcx);
    GEN_OFFSET(TRAP_FRAME, rdx);
    GEN_OFFSET(TRAP_FRAME, rsi);
    GEN_OFFSET(TRAP_FRAME, rdi);
    GEN_OFFSET(TRAP_FRAME, rbp);
    GEN_OFFSET(TRAP_FRAME, r8);
    GEN_OFFSET(TRAP_FRAME, r9);
    GEN_OFFSET(TRAP_FRAME, r10);
    GEN_OFFSET(TRAP_FRAME, r11);
    GEN_OFFSET(TRAP_FRAME, r12);
    GEN_OFFSET(TRAP_FRAME, r13);
    GEN_OFFSET(TRAP_FRAME, r14);
    GEN_OFFSET(TRAP_FRAME, r15);
    GEN_OFFSET(TRAP_FRAME, vector);
    GEN_OFFSET(TRAP_FRAME, error_code);
    GEN_OFFSET(TRAP_FRAME, rip);
    GEN_OFFSET(TRAP_FRAME, cs);
    GEN_OFFSET(TRAP_FRAME, rflags);
    GEN_OFFSET(TRAP_FRAME, rsp);
    GEN_OFFSET(TRAP_FRAME, ss);
    GEN_SIZE(TRAP_FRAME);

    GEN_COMMENT("ITHREAD Offsets (Internal Thread)");
    GEN_OFFSET(ITHREAD, TrapRegisters);
    GEN_OFFSET(ITHREAD, ThreadState);
    GEN_OFFSET(ITHREAD, StackBase);
    GEN_OFFSET(ITHREAD, IsLargeStack);
    GEN_OFFSET(ITHREAD, NextThread);
    GEN_OFFSET(ITHREAD, PreviousMode);

    GEN_COMMENT("Processor Constants");
    GEN_DEFINE(KERNEL_CS, KERNEL_CS);
    GEN_DEFINE(KERNEL_DS, KERNEL_DS);
    GEN_DEFINE(USER_CS, USER_CS);
    GEN_DEFINE(USER_DS, USER_DS);
    GEN_DEFINE(INITIAL_RFLAGS, INITIAL_RFLAGS);
    GEN_DEFINE(USER_RFLAGS, USER_RFLAGS);
    GEN_DEFINE(MAX_CPUS, MAX_CPUS);

    GEN_COMMENT("Bugcheck Codes");
    GEN_DEFINE(IRQL_NOT_LESS_OR_EQUAL, IRQL_NOT_LESS_OR_EQUAL);
    GEN_DEFINE(IRQL_NOT_GREATER_OR_EQUAL, IRQL_NOT_GREATER_OR_EQUAL);
    GEN_DEFINE(KERNEL_STACK_OVERFLOWN, KERNEL_STACK_OVERFLOWN);
    GEN_DEFINE(MANUALLY_INITIATED_CRASH, MANUALLY_INITIATED_CRASH);
    GEN_DEFINE(PAGE_FAULT, PAGE_FAULT);
    GEN_DEFINE(DOUBLE_FAULT, DOUBLE_FAULT);
    GEN_DEFINE(GENERAL_PROTECTION_FAULT, GENERAL_PROTECTION_FAULT);
    GEN_DEFINE(ATTEMPTED_SWITCH_FROM_DPC, ATTEMPTED_SWITCH_FROM_DPC);

    GEN_COMMENT("IRQL Levels");
    GEN_DEFINE(PASSIVE_LEVEL, PASSIVE_LEVEL);
    GEN_DEFINE(DISPATCH_LEVEL, DISPATCH_LEVEL);
    GEN_DEFINE(PROFILE_LEVEL, PROFILE_LEVEL);
    GEN_DEFINE(CLOCK_LEVEL, CLOCK_LEVEL);
    GEN_DEFINE(IPI_LEVEL, IPI_LEVEL);
    GEN_DEFINE(POWER_LEVEL, POWER_LEVEL);
    GEN_DEFINE(HIGH_LEVEL, HIGH_LEVEL);

    // ========================================================================
    // 2. PROCESS & THREAD (ps.h)
    // ========================================================================
    GEN_COMMENT("EPROCESS Offsets");
    GEN_OFFSET(EPROCESS, InternalProcess);
    GEN_OFFSET(EPROCESS, PID);
    GEN_OFFSET(EPROCESS, ParentProcess);
    GEN_OFFSET(EPROCESS, MainThread);
    GEN_OFFSET(EPROCESS, VadRoot);
    GEN_OFFSET(EPROCESS, NextStackTop);

    GEN_COMMENT("ETHREAD Offsets");
    GEN_OFFSET(ETHREAD, InternalThread);
    GEN_OFFSET(ETHREAD, TID);
    GEN_OFFSET(ETHREAD, ParentProcess);
    GEN_OFFSET(ETHREAD, CurrentEvent);

    GEN_COMMENT("Thread State Enums");
    GEN_DEFINE(THREAD_RUNNING, THREAD_RUNNING);
    GEN_DEFINE(THREAD_READY, THREAD_READY);
    GEN_DEFINE(THREAD_TERMINATED, THREAD_TERMINATED);

    // ========================================================================
    // 3. MEMORY SYSTEM (mm.h)
    // ========================================================================
    GEN_COMMENT("Memory Management Constants");
    GEN_DEFINE(VirtualPageSize, VirtualPageSize);
    GEN_DEFINE(KernelVaStart, KernelVaStart);
    // Note: PhysicalMemoryOffset is a large ULL, we cast to preserve generic print
    GEN_DEFINE(PhysicalMemoryOffset, PhysicalMemoryOffset);

    GEN_COMMENT("MMPTE Offsets & Flags");
    GEN_OFFSET(MMPTE, Value);
    GEN_DEFINE(PAGE_PRESENT, PAGE_PRESENT);
    GEN_DEFINE(PAGE_RW, PAGE_RW);
    GEN_DEFINE(PAGE_USER, PAGE_USER);
    GEN_DEFINE(PAGE_NX, PAGE_NX);

    // ========================================================================
    // 4. SYNCHRONIZATION (ms.h)
    // ========================================================================
    GEN_COMMENT("Spinlock & Mutex");
    GEN_OFFSET(SPINLOCK, locked);
    GEN_OFFSET(MUTEX, ownerTid);
    GEN_OFFSET(MUTEX, locked);
    GEN_OFFSET(MUTEX, ownerThread);

    return 0;
}