.TH "_AHCI_PORT_CTX" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AHCI_PORT_CTX
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBHBA_PORT\fP * \fBport\fP"
.br
.ti -1c
.RI "\fBHBA_CMD_TBL\fP * \fBcmd_tbl\fP"
.br
.ti -1c
.RI "void * \fBclb\fP"
.br
.ti -1c
.RI "void * \fBfis\fP"
.br
.ti -1c
.RI "\fBBLOCK_DEVICE\fP \fBbdev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBahci\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBBLOCK_DEVICE\fP bdev"

.PP
Definition at line \fB51\fP of file \fBahci\&.c\fP\&.
.SS "void* clb"

.PP
Definition at line \fB49\fP of file \fBahci\&.c\fP\&.
.SS "\fBHBA_CMD_TBL\fP* cmd_tbl"

.PP
Definition at line \fB48\fP of file \fBahci\&.c\fP\&.
.SS "void* fis"

.PP
Definition at line \fB50\fP of file \fBahci\&.c\fP\&.
.SS "\fBHBA_PORT\fP* port"

.PP
Definition at line \fB47\fP of file \fBahci\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
