.TH "_BOOT_INFO" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_BOOT_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <uefi_memory\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGOP_PARAMS\fP * \fBGop\fP"
.br
.ti -1c
.RI "\fBEFI_MEMORY_DESCRIPTOR\fP * \fBMemoryMap\fP"
.br
.ti -1c
.RI "size_t \fBMapSize\fP"
.br
.ti -1c
.RI "size_t \fBDescriptorSize\fP"
.br
.ti -1c
.RI "uint32_t \fBDescriptorVersion\fP"
.br
.ti -1c
.RI "size_t \fBAhciCount\fP"
.br
.ti -1c
.RI "uint64_t * \fBAhciBarBases\fP"
.br
.ti -1c
.RI "uint64_t \fBKernelStackTop\fP"
.br
.ti -1c
.RI "uintptr_t \fBPml4Phys\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBuefi_memory\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t* AhciBarBases"

.PP
Definition at line \fB39\fP of file \fBuefi_memory\&.h\fP\&.
.SS "size_t AhciCount"

.PP
Definition at line \fB38\fP of file \fBuefi_memory\&.h\fP\&.
.SS "size_t DescriptorSize"

.PP
Definition at line \fB36\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint32_t DescriptorVersion"

.PP
Definition at line \fB37\fP of file \fBuefi_memory\&.h\fP\&.
.SS "\fBGOP_PARAMS\fP* Gop"

.PP
Definition at line \fB33\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint64_t KernelStackTop"

.PP
Definition at line \fB40\fP of file \fBuefi_memory\&.h\fP\&.
.SS "size_t MapSize"

.PP
Definition at line \fB35\fP of file \fBuefi_memory\&.h\fP\&.
.SS "\fBEFI_MEMORY_DESCRIPTOR\fP* MemoryMap"

.PP
Definition at line \fB34\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uintptr_t Pml4Phys"

.PP
Definition at line \fB41\fP of file \fBuefi_memory\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
