.TH "_CPU" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_CPU
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cpu_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIRQL\fP \fBcurrentIrql\fP"
.br
.ti -1c
.RI "bool \fBschedulerEnabled\fP"
.br
.ti -1c
.RI "\fBThread\fP * \fBcurrentThread\fP"
.br
.ti -1c
.RI "\fBQueue\fP \fBreadyQueue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB148\fP of file \fBcpu_types\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBIRQL\fP currentIrql"

.PP
Definition at line \fB149\fP of file \fBcpu_types\&.h\fP\&.
.SS "\fBThread\fP* currentThread"

.PP
Definition at line \fB151\fP of file \fBcpu_types\&.h\fP\&.
.SS "\fBQueue\fP readyQueue"

.PP
Definition at line \fB152\fP of file \fBcpu_types\&.h\fP\&.
.SS "bool schedulerEnabled"

.PP
Definition at line \fB150\fP of file \fBcpu_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
