.TH "_FIS_REG_H2D" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_FIS_REG_H2D \- Register - Host to Device FIS (FIS_TYPE_REG_H2D)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ahci\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBfis_type\fP"
.br
.ti -1c
.RI "uint8_t \fBpmport\fP: 4"
.br
.ti -1c
.RI "uint8_t \fBrsv0\fP: 3"
.br
.ti -1c
.RI "uint8_t \fBc\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBcommand\fP"
.br
.ti -1c
.RI "uint8_t \fBfeaturel\fP"
.br
.ti -1c
.RI "uint8_t \fBlba0\fP"
.br
.ti -1c
.RI "uint8_t \fBlba1\fP"
.br
.ti -1c
.RI "uint8_t \fBlba2\fP"
.br
.ti -1c
.RI "uint8_t \fBdevice\fP"
.br
.ti -1c
.RI "uint8_t \fBlba3\fP"
.br
.ti -1c
.RI "uint8_t \fBlba4\fP"
.br
.ti -1c
.RI "uint8_t \fBlba5\fP"
.br
.ti -1c
.RI "uint8_t \fBfeatureh\fP"
.br
.ti -1c
.RI "uint8_t \fBcountl\fP"
.br
.ti -1c
.RI "uint8_t \fBcounth\fP"
.br
.ti -1c
.RI "uint8_t \fBicc\fP"
.br
.ti -1c
.RI "uint8_t \fBcontrol\fP"
.br
.ti -1c
.RI "uint8_t \fBrsv1\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Register - Host to Device FIS (FIS_TYPE_REG_H2D) 
.PP
Definition at line \fB75\fP of file \fBahci\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t c"

.PP
Definition at line \fB79\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t command"

.PP
Definition at line \fB80\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t control"

.PP
Definition at line \fB93\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t counth"

.PP
Definition at line \fB91\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t countl"

.PP
Definition at line \fB90\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t device"

.PP
Definition at line \fB85\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t featureh"

.PP
Definition at line \fB89\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t featurel"

.PP
Definition at line \fB81\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t fis_type"

.PP
Definition at line \fB76\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t icc"

.PP
Definition at line \fB92\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t lba0"

.PP
Definition at line \fB82\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t lba1"

.PP
Definition at line \fB83\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t lba2"

.PP
Definition at line \fB84\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t lba3"

.PP
Definition at line \fB86\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t lba4"

.PP
Definition at line \fB87\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t lba5"

.PP
Definition at line \fB88\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t pmport"

.PP
Definition at line \fB77\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t rsv0"

.PP
Definition at line \fB78\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t rsv1[4]"

.PP
Definition at line \fB94\fP of file \fBahci\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
