.TH "_HBA_PORT" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HBA_PORT \- Per port registers at \fBHBA_MEM\fP + 0x100 + (port * 0x80)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ahci\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBclb\fP"
.br
.ti -1c
.RI "uint32_t \fBclbu\fP"
.br
.ti -1c
.RI "uint32_t \fBfb\fP"
.br
.ti -1c
.RI "uint32_t \fBfbu\fP"
.br
.ti -1c
.RI "uint32_t \fBis\fP"
.br
.ti -1c
.RI "uint32_t \fBie\fP"
.br
.ti -1c
.RI "uint32_t \fBcmd\fP"
.br
.ti -1c
.RI "uint32_t \fBrsv0\fP"
.br
.ti -1c
.RI "uint32_t \fBtfd\fP"
.br
.ti -1c
.RI "uint32_t \fBsig\fP"
.br
.ti -1c
.RI "uint32_t \fBssts\fP"
.br
.ti -1c
.RI "uint32_t \fBsctl\fP"
.br
.ti -1c
.RI "uint32_t \fBserr\fP"
.br
.ti -1c
.RI "uint32_t \fBsact\fP"
.br
.ti -1c
.RI "uint32_t \fBci\fP"
.br
.ti -1c
.RI "uint32_t \fBsntf\fP"
.br
.ti -1c
.RI "uint32_t \fBfbs\fP"
.br
.ti -1c
.RI "uint32_t \fBrsv1\fP [11]"
.br
.ti -1c
.RI "uint32_t \fBvendor\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Per port registers at \fBHBA_MEM\fP + 0x100 + (port * 0x80) 
.PP
Definition at line \fB49\fP of file \fBahci\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t ci"

.PP
Definition at line \fB64\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t clb"

.PP
Definition at line \fB50\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t clbu"

.PP
Definition at line \fB51\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t cmd"

.PP
Definition at line \fB56\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t fb"

.PP
Definition at line \fB52\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t fbs"

.PP
Definition at line \fB66\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t fbu"

.PP
Definition at line \fB53\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t ie"

.PP
Definition at line \fB55\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t is"

.PP
Definition at line \fB54\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t rsv0"

.PP
Definition at line \fB57\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t rsv1[11]"

.PP
Definition at line \fB67\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t sact"

.PP
Definition at line \fB63\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t sctl"

.PP
Definition at line \fB61\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t serr"

.PP
Definition at line \fB62\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t sig"

.PP
Definition at line \fB59\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t sntf"

.PP
Definition at line \fB65\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t ssts"

.PP
Definition at line \fB60\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t tfd"

.PP
Definition at line \fB58\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t vendor[4]"

.PP
Definition at line \fB68\fP of file \fBahci\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
