.TH "_HBA_MEM" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HBA_MEM \- AHCI Register layout (Global HBA Registers)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ahci\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBcap\fP"
.br
.ti -1c
.RI "uint32_t \fBghc\fP"
.br
.ti -1c
.RI "uint32_t \fBis\fP"
.br
.ti -1c
.RI "uint32_t \fBpi\fP"
.br
.ti -1c
.RI "uint32_t \fBvs\fP"
.br
.ti -1c
.RI "uint32_t \fBccc_ctl\fP"
.br
.ti -1c
.RI "uint32_t \fBccc_pts\fP"
.br
.ti -1c
.RI "uint32_t \fBem_loc\fP"
.br
.ti -1c
.RI "uint32_t \fBem_ctl\fP"
.br
.ti -1c
.RI "uint32_t \fBcap2\fP"
.br
.ti -1c
.RI "uint32_t \fBbohc\fP"
.br
.ti -1c
.RI "uint8_t \fBrsv\fP [0xA0 \- 0x2C]"
.br
.ti -1c
.RI "uint8_t \fBvenor\fP [0x100 \- 0xA0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
AHCI Register layout (Global HBA Registers) 
.PP
Definition at line \fB31\fP of file \fBahci\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t bohc"

.PP
Definition at line \fB42\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t cap"

.PP
Definition at line \fB32\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t cap2"

.PP
Definition at line \fB41\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t ccc_ctl"

.PP
Definition at line \fB37\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t ccc_pts"

.PP
Definition at line \fB38\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t em_ctl"

.PP
Definition at line \fB40\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t em_loc"

.PP
Definition at line \fB39\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t ghc"

.PP
Definition at line \fB33\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t is"

.PP
Definition at line \fB34\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t pi"

.PP
Definition at line \fB35\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t rsv[0xA0 \- 0x2C]"

.PP
Definition at line \fB43\fP of file \fBahci\&.h\fP\&.
.SS "uint8_t venor[0x100 \- 0xA0]"

.PP
Definition at line \fB44\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t vs"

.PP
Definition at line \fB36\fP of file \fBahci\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
