.TH "_INT_FRAME" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_INT_FRAME
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cpu_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvector\fP"
.br
.ti -1c
.RI "uint64_t \fBerror_code\fP"
.br
.ti -1c
.RI "uint64_t \fBrip\fP"
.br
.ti -1c
.RI "uint64_t \fBcs\fP"
.br
.ti -1c
.RI "uint64_t \fBrflags\fP"
.br
.ti -1c
.RI "uint64_t \fBrsp\fP"
.br
.ti -1c
.RI "uint64_t \fBss\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBcpu_types\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t cs"

.PP
Definition at line \fB60\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t error_code"

.PP
Definition at line \fB58\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rflags"

.PP
Definition at line \fB61\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rip"

.PP
Definition at line \fB59\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rsp"

.PP
Definition at line \fB62\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t ss"

.PP
Definition at line \fB63\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t vector"

.PP
Definition at line \fB57\fP of file \fBcpu_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
