.TH "_Thread" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Thread
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cpu_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCTX_FRAME\fP \fBregisters\fP"
.br
.ti -1c
.RI "\fBTHREAD_STATE\fP \fBthreadState\fP"
.br
.ti -1c
.RI "uint32_t \fBtimeSlice\fP"
.br
.ti -1c
.RI "uint32_t \fBorigTimeSlice\fP"
.br
.ti -1c
.RI "\fBThread\fP * \fBnextThread\fP"
.br
.ti -1c
.RI "uint32_t \fBTID\fP"
.br
.ti -1c
.RI "void * \fBstartStackPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB103\fP of file \fBcpu_types\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBThread\fP* nextThread"

.PP
Definition at line \fB114\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint32_t origTimeSlice"

.PP
Definition at line \fB112\fP of file \fBcpu_types\&.h\fP\&.
.SS "\fBCTX_FRAME\fP registers"

.PP
Definition at line \fB105\fP of file \fBcpu_types\&.h\fP\&.
.SS "void* startStackPtr"

.PP
Definition at line \fB120\fP of file \fBcpu_types\&.h\fP\&.
.SS "\fBTHREAD_STATE\fP threadState"

.PP
Definition at line \fB108\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint32_t TID"

.PP
Definition at line \fB117\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint32_t timeSlice"

.PP
Definition at line \fB111\fP of file \fBcpu_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
