.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/dpc Directory Reference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/dpc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdpc\&.c\fP"
.br
.ti -1c
.RI "file \fBdpc\&.h\fP"
.br
.ti -1c
.RI "file \fBdpc_list\&.c\fP"
.br
.ti -1c
.RI "file \fBdpc_list\&.h\fP"
.br
.in -1c
