.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/intrin Directory Reference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/intrin Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBatomic\&.h\fP"
.br
.ti -1c
.RI "file \fBintrin\&.h\fP"
.br
.in -1c
