.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/filesystem/vfs Directory Reference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/filesystem/vfs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBvfs\&.c\fP"
.br
.ti -1c
.RI "file \fBvfs\&.h\fP"
.br
.in -1c
