.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/irql Directory Reference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/irql Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBirql\&.c\fP"
.br
.ti -1c
.RI "file \fBirql\&.h\fP"
.br
.in -1c
