.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/dpc/dpc_list.c" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/dpc/dpc_list.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./cpu\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBScheduleDPC\fP (void)"
.br
.RI "ScheduleDPC, used to enable the Scheduling_needed flag to TRUE\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile bool \fBschedule_pending\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ScheduleDPC (void )"

.PP
ScheduleDPC, used to enable the Scheduling_needed flag to TRUE\&. 
.PP
Definition at line \fB10\fP of file \fBdpc_list\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "volatile bool schedule_pending\fR [extern]\fP"

.PP
Definition at line \fB13\fP of file \fBdpc\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
