.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/drivers/gop/gop.c" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/drivers/gop/gop.c
.SH SYNOPSIS
.br
.PP
\fR#include 'gop\&.h'\fP
.br
\fR#include 'font8x16\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFONT8X16_IMPLEMENTATION\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdraw_char\fP (\fBGOP_PARAMS\fP *gop, char c_, uint32_t x, uint32_t y, uint32_t color)"
.br
.ti -1c
.RI "void \fBdraw_string\fP (\fBGOP_PARAMS\fP *gop, const char *s, uint32_t x, uint32_t y, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_scroll\fP (\fBGOP_PARAMS\fP *gop)"
.br
.ti -1c
.RI "void \fBgop_put_char\fP (\fBGOP_PARAMS\fP *gop, char c, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_puts\fP (\fBGOP_PARAMS\fP *gop, const char *s, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_print_dec\fP (\fBGOP_PARAMS\fP *gop, unsigned val, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_print_hex\fP (\fBGOP_PARAMS\fP *gop, uint64_t val, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_clear_screen\fP (\fBGOP_PARAMS\fP *gop, uint32_t color)"
.br
.ti -1c
.RI "char * \fBkstrncat\fP (char *dest, const char *src, size_t max_len)"
.br
.RI "Concatenates src onto dest, up to max_len total bytes in dest\&. "
.ti -1c
.RI "size_t \fBkstrlen\fP (const char *str)"
.br
.ti -1c
.RI "char * \fBkstrcpy\fP (char *dst, const char *src)"
.br
.ti -1c
.RI "char * \fBkstrtok\fP (char *str, const char *delim)"
.br
.ti -1c
.RI "int \fBksnprintf\fP (char *buf, size_t bufsize, const char *fmt,\&.\&.\&.)"
.br
.RI "snprintf equivalent\&. -- Safe to run at ANY \fBIRQL\fP\&. "
.ti -1c
.RI "int \fBkstrcmp\fP (const char *s1, const char *s2)"
.br
.ti -1c
.RI "void \fBgop_printf\fP (uint32_t color, const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBgop_bold_enabled\fP = false"
.br
.ti -1c
.RI "uint32_t \fBcursor_x\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBcursor_y\fP = 0"
.br
.ti -1c
.RI "\fBGOP_PARAMS\fP \fBgop_local\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FONT8X16_IMPLEMENTATION"

.PP
Definition at line \fB8\fP of file \fBgop\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void draw_char (\fBGOP_PARAMS\fP * gop, char c_, uint32_t x, uint32_t y, uint32_t color)"

.PP
Definition at line \fB15\fP of file \fBgop\&.c\fP\&.
.SS "void draw_string (\fBGOP_PARAMS\fP * gop, const char * s, uint32_t x, uint32_t y, uint32_t color)"

.PP
Definition at line \fB50\fP of file \fBgop\&.c\fP\&.
.SS "void gop_clear_screen (\fBGOP_PARAMS\fP * gop, uint32_t color)"

.PP
Definition at line \fB157\fP of file \fBgop\&.c\fP\&.
.SS "void gop_print_dec (\fBGOP_PARAMS\fP * gop, unsigned val, uint32_t color)"

.PP
Definition at line \fB139\fP of file \fBgop\&.c\fP\&.
.SS "void gop_print_hex (\fBGOP_PARAMS\fP * gop, uint64_t val, uint32_t color)"

.PP
Definition at line \fB145\fP of file \fBgop\&.c\fP\&.
.SS "void gop_printf (uint32_t color, const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB398\fP of file \fBgop\&.c\fP\&.
.SS "void gop_put_char (\fBGOP_PARAMS\fP * gop, char c, uint32_t color)"

.PP
Definition at line \fB78\fP of file \fBgop\&.c\fP\&.
.SS "void gop_puts (\fBGOP_PARAMS\fP * gop, const char * s, uint32_t color)"

.PP
Definition at line \fB119\fP of file \fBgop\&.c\fP\&.
.SS "void gop_scroll (\fBGOP_PARAMS\fP * gop)"

.PP
Definition at line \fB58\fP of file \fBgop\&.c\fP\&.
.SS "int ksnprintf (char * buf, size_t bufsize, const char * fmt,  \&.\&.\&.)"

.PP
snprintf equivalent\&. -- Safe to run at ANY \fBIRQL\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuf\fP Buffer to format\&.
.br
\fIbufSize\fP Size of the buffer\&.
.br
\fIfmt\fP String and format\&.
.RE
.PP
<return>Amount of bytes written\&. (excluding null terminator)</return> 
.PP
Definition at line \fB323\fP of file \fBgop\&.c\fP\&.
.SS "int kstrcmp (const char * s1, const char * s2)"

.PP
Definition at line \fB389\fP of file \fBgop\&.c\fP\&.
.SS "char * kstrcpy (char * dst, const char * src)"

.PP
Definition at line \fB273\fP of file \fBgop\&.c\fP\&.
.SS "size_t kstrlen (const char * str)"

.PP
Definition at line \fB262\fP of file \fBgop\&.c\fP\&.
.SS "char * kstrncat (char * dest, const char * src, size_t max_len)"

.PP
Concatenates src onto dest, up to max_len total bytes in dest\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP Destination buffer (must be mutable)
.br
\fIsrc\fP String to append
.br
\fImax_len\fP Total size of the destination buffer
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to dest
.RE
.PP

.PP
Definition at line \fB234\fP of file \fBgop\&.c\fP\&.
.SS "char * kstrtok (char * str, const char * delim)"

.PP
Definition at line \fB286\fP of file \fBgop\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint32_t cursor_x = 0"

.PP
Definition at line \fB12\fP of file \fBgop\&.c\fP\&.
.SS "uint32_t cursor_y = 0"

.PP
Definition at line \fB12\fP of file \fBgop\&.c\fP\&.
.SS "bool gop_bold_enabled = false"

.PP
Definition at line \fB11\fP of file \fBgop\&.c\fP\&.
.SS "\fBGOP_PARAMS\fP gop_local\fR [extern]\fP"

.PP
Definition at line \fB155\fP of file \fBgop\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
