.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/irql/irql.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/irql/irql.h
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include '\&.\&./\&.\&./trace\&.h'\fP
.br
\fR#include '\&.\&./cpu_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupdate_pic_mask_for_current_irql\fP (void)"
.br
.ti -1c
.RI "void \fBMtGetCurrentIRQL\fP (\fBIRQL\fP *current_irql)"
.br
.ti -1c
.RI "void \fBMtRaiseIRQL\fP (\fBIRQL\fP new_irql, \fBIRQL\fP *old_irql)"
.br
.ti -1c
.RI "void \fBMtLowerIRQL\fP (\fBIRQL\fP new_irql)"
.br
.ti -1c
.RI "void \fB_MtSetIRQL\fP (\fBIRQL\fP new_irql)"
.br
.ti -1c
.RI "void \fBenforce_max_irql\fP (\fBIRQL\fP max_allowed, void *RIP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCPU\fP \fBcpu\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _MtSetIRQL (\fBIRQL\fP new_irql)"

.PP
Definition at line \fB100\fP of file \fBirql\&.c\fP\&.
.SS "void enforce_max_irql (\fBIRQL\fP max_allowed, void * RIP)"

.PP
Definition at line \fB111\fP of file \fBirql\&.c\fP\&.
.SS "void MtGetCurrentIRQL (\fBIRQL\fP * current_irql)"

.PP
Definition at line \fB50\fP of file \fBirql\&.c\fP\&.
.SS "void MtLowerIRQL (\fBIRQL\fP new_irql)"

.PP
Definition at line \fB79\fP of file \fBirql\&.c\fP\&.
.SS "void MtRaiseIRQL (\fBIRQL\fP new_irql, \fBIRQL\fP * old_irql)"

.PP
Definition at line \fB55\fP of file \fBirql\&.c\fP\&.
.SS "void update_pic_mask_for_current_irql (void )"

.PP
Definition at line \fB27\fP of file \fBirql\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCPU\fP cpu\fR [extern]\fP"

.PP
Definition at line \fB23\fP of file \fBkernel\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
