.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/apic/pit.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/apic/pit.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpit_sleep_ms\fP (uint32_t ms)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pit_sleep_ms (uint32_t ms)"

.PP
Definition at line \fB22\fP of file \fBpit\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
