.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/time.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/time.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include 'intrin/intrin\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTIME_ENTRY\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCMOS_ADDRESS\fP   0x70"
.br
.ti -1c
.RI "#define \fBCMOS_DATA\fP   0x71"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CMOS_ADDRESS   0x70"

.PP
Definition at line \fB14\fP of file \fBtime\&.h\fP\&.
.SS "#define CMOS_DATA   0x71"

.PP
Definition at line \fB15\fP of file \fBtime\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
