.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/trace.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/trace.h
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include 'intrin/intrin\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLASTFUNC_HISTORY\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLASTFUNC_BUFFER_SIZE\fP   128"
.br
.ti -1c
.RI "#define \fBLASTFUNC_HISTORY_SIZE\fP   10"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LASTFUNC_BUFFER_SIZE   128"

.PP
Definition at line \fB10\fP of file \fBtrace\&.h\fP\&.
.SS "#define LASTFUNC_HISTORY_SIZE   10"

.PP
Definition at line \fB11\fP of file \fBtrace\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
