/* Error codes shared by public user headers and mtdll internals. */

#ifndef MATANELOS_SHARED_ERRORCODES_H
#define MATANELOS_SHARED_ERRORCODES_H

#include <stdint.h>

typedef int32_t ERROR_CODE;

#define ERROR_SUCCESS                 ((ERROR_CODE)0L)
#define ERROR_INVALID_FUNCTION        ((ERROR_CODE)1L)
#define ERROR_FILE_NOT_FOUND          ((ERROR_CODE)2L)
#define ERROR_PATH_NOT_FOUND          ((ERROR_CODE)3L)
#define ERROR_TOO_MANY_OPEN_FILES     ((ERROR_CODE)4L)
#define ERROR_ACCESS_DENIED           ((ERROR_CODE)5L)
#define ERROR_INVALID_HANDLE          ((ERROR_CODE)6L)
#define ERROR_NOT_ENOUGH_MEMORY       ((ERROR_CODE)8L)
#define ERROR_INVALID_DATA            ((ERROR_CODE)13L)
#define ERROR_OUTOFMEMORY             ((ERROR_CODE)14L)
#define ERROR_INVALID_DRIVE           ((ERROR_CODE)15L)
#define ERROR_NO_MORE_FILES           ((ERROR_CODE)18L)
#define ERROR_WRITE_PROTECT           ((ERROR_CODE)19L)
#define ERROR_BAD_UNIT                ((ERROR_CODE)20L)
#define ERROR_NOT_READY               ((ERROR_CODE)21L)
#define ERROR_BAD_COMMAND             ((ERROR_CODE)22L)
#define ERROR_CRC                     ((ERROR_CODE)23L)
#define ERROR_BAD_LENGTH              ((ERROR_CODE)24L)
#define ERROR_SEEK                    ((ERROR_CODE)25L)
#define ERROR_NOT_DOS_DISK            ((ERROR_CODE)26L)
#define ERROR_SECTOR_NOT_FOUND        ((ERROR_CODE)27L)
#define ERROR_OUT_OF_PAPER            ((ERROR_CODE)28L)
#define ERROR_WRITE_FAULT             ((ERROR_CODE)29L)
#define ERROR_READ_FAULT              ((ERROR_CODE)30L)
#define ERROR_GEN_FAILURE             ((ERROR_CODE)31L)
#define ERROR_SHARING_VIOLATION       ((ERROR_CODE)32L)
#define ERROR_LOCK_VIOLATION          ((ERROR_CODE)33L)
#define ERROR_WRONG_DISK              ((ERROR_CODE)34L)
#define ERROR_HANDLE_EOF              ((ERROR_CODE)38L)
#define ERROR_HANDLE_DISK_FULL        ((ERROR_CODE)39L)
#define ERROR_NOT_SUPPORTED           ((ERROR_CODE)50L)
#define ERROR_FILE_EXISTS             ((ERROR_CODE)80L)
#define ERROR_INVALID_PARAMETER       ((ERROR_CODE)87L)
#define ERROR_BROKEN_PIPE             ((ERROR_CODE)109L)
#define ERROR_BUFFER_OVERFLOW         ((ERROR_CODE)111L)
#define ERROR_DISK_FULL               ((ERROR_CODE)112L)
#define ERROR_NOT_IMPLEMENTED         ((ERROR_CODE)120L)
#define ERROR_INVALID_NAME            ((ERROR_CODE)123L)
#define ERROR_MOD_NOT_FOUND           ((ERROR_CODE)126L)
#define ERROR_PROC_NOT_FOUND          ((ERROR_CODE)127L)
#define ERROR_DIR_NOT_EMPTY           ((ERROR_CODE)145L)
#define ERROR_BAD_PATHNAME            ((ERROR_CODE)161L)
#define ERROR_ALREADY_EXISTS          ((ERROR_CODE)183L)
#define ERROR_FILENAME_EXCED_RANGE    ((ERROR_CODE)206L)
#define ERROR_DIRECTORY               ((ERROR_CODE)267L)
#define ERROR_TOO_MANY_POSTS          ((ERROR_CODE)298L)
#define ERROR_OPERATION_ABORTED       ((ERROR_CODE)995L)
#define ERROR_IO_INCOMPLETE           ((ERROR_CODE)996L)
#define ERROR_IO_PENDING              ((ERROR_CODE)997L)
#define ERROR_NOACCESS                ((ERROR_CODE)998L)
#define ERROR_IO_DEVICE               ((ERROR_CODE)1117L)
#define ERROR_NOT_FOUND               ((ERROR_CODE)1168L)
#define ERROR_TIMEOUT                 ((ERROR_CODE)1460L)
#define ERROR_DATATYPE_MISMATCH       ((ERROR_CODE)1629L)
#define ERROR_NOT_ENOUGH_QUOTA        ((ERROR_CODE)1816L)

#endif /* MATANELOS_SHARED_ERRORCODES_H */
