.TH "_BLOCK_DEVICE" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_BLOCK_DEVICE
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <block\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMTSTATUS\fP(* \fBread_sector\fP )(struct \fB_BLOCK_DEVICE\fP *dev, uint32_t lba, void *buf)"
.br
.ti -1c
.RI "\fBMTSTATUS\fP(* \fBwrite_sector\fP )(struct \fB_BLOCK_DEVICE\fP *dev, uint32_t lba, const void *buf)"
.br
.ti -1c
.RI "void * \fBdev_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBblock\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "void* dev_data"

.PP
Definition at line \fB21\fP of file \fBblock\&.h\fP\&.
.SS "\fBMTSTATUS\fP(* read_sector) (struct \fB_BLOCK_DEVICE\fP *dev, uint32_t lba, void *buf)"

.PP
Definition at line \fB15\fP of file \fBblock\&.h\fP\&.
.SS "\fBMTSTATUS\fP(* write_sector) (struct \fB_BLOCK_DEVICE\fP *dev, uint32_t lba, const void *buf)"

.PP
Definition at line \fB18\fP of file \fBblock\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
