.TH "_BUGCHECK_ADDITIONALS" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_BUGCHECK_ADDITIONALS
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bugcheck\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstr\fP [512]"
.br
.ti -1c
.RI "uint64_t \fBnum\fP"
.br
.ti -1c
.RI "int64_t \fBsignednum\fP"
.br
.ti -1c
.RI "bool \fBboolean\fP"
.br
.ti -1c
.RI "void * \fBptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB62\fP of file \fBbugcheck\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool boolean"

.PP
Definition at line \fB70\fP of file \fBbugcheck\&.h\fP\&.
.SS "uint64_t num"

.PP
Definition at line \fB66\fP of file \fBbugcheck\&.h\fP\&.
.SS "void* ptr"

.PP
Definition at line \fB72\fP of file \fBbugcheck\&.h\fP\&.
.SS "int64_t signednum"

.PP
Definition at line \fB68\fP of file \fBbugcheck\&.h\fP\&.
.SS "char str[512]"

.PP
Definition at line \fB64\fP of file \fBbugcheck\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
