.TH "_CTX_FRAME" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_CTX_FRAME
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cpu_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBr15\fP"
.br
.ti -1c
.RI "uint64_t \fBr14\fP"
.br
.ti -1c
.RI "uint64_t \fBr13\fP"
.br
.ti -1c
.RI "uint64_t \fBr12\fP"
.br
.ti -1c
.RI "uint64_t \fBr11\fP"
.br
.ti -1c
.RI "uint64_t \fBr10\fP"
.br
.ti -1c
.RI "uint64_t \fBr9\fP"
.br
.ti -1c
.RI "uint64_t \fBr8\fP"
.br
.ti -1c
.RI "uint64_t \fBrbp\fP"
.br
.ti -1c
.RI "uint64_t \fBrdi\fP"
.br
.ti -1c
.RI "uint64_t \fBrsi\fP"
.br
.ti -1c
.RI "uint64_t \fBrdx\fP"
.br
.ti -1c
.RI "uint64_t \fBrcx\fP"
.br
.ti -1c
.RI "uint64_t \fBrbx\fP"
.br
.ti -1c
.RI "uint64_t \fBrax\fP"
.br
.ti -1c
.RI "uint64_t \fBrsp\fP"
.br
.ti -1c
.RI "uint64_t \fBrip\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB69\fP of file \fBcpu_types\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t r10"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t r11"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t r12"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t r13"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t r14"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t r15"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t r8"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t r9"

.PP
Definition at line \fB71\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rax"

.PP
Definition at line \fB72\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rbp"

.PP
Definition at line \fB72\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rbx"

.PP
Definition at line \fB72\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rcx"

.PP
Definition at line \fB72\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rdi"

.PP
Definition at line \fB72\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rdx"

.PP
Definition at line \fB72\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rip"

.PP
Definition at line \fB74\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rsi"

.PP
Definition at line \fB72\fP of file \fBcpu_types\&.h\fP\&.
.SS "uint64_t rsp"

.PP
Definition at line \fB73\fP of file \fBcpu_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
