.TH "_EFI_MEMORY_DESCRIPTOR" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_EFI_MEMORY_DESCRIPTOR
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <uefi_memory\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBType\fP"
.br
.ti -1c
.RI "uint32_t \fBPad\fP"
.br
.ti -1c
.RI "uint64_t \fBPhysicalStart\fP"
.br
.ti -1c
.RI "uint64_t \fBVirtualStart\fP"
.br
.ti -1c
.RI "uint64_t \fBNumberOfPages\fP"
.br
.ti -1c
.RI "uint64_t \fBAttribute\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBuefi_memory\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t Attribute"

.PP
Definition at line \fB21\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint64_t NumberOfPages"

.PP
Definition at line \fB20\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint32_t Pad"

.PP
Definition at line \fB17\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint64_t PhysicalStart"

.PP
Definition at line \fB18\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint32_t Type"

.PP
Definition at line \fB16\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint64_t VirtualStart"

.PP
Definition at line \fB19\fP of file \fBuefi_memory\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
