.TH "_FAT32_FSINFO" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_FAT32_FSINFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fat32\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBfirst_data_sector\fP"
.br
.ti -1c
.RI "uint32_t \fBroot_cluster\fP"
.br
.ti -1c
.RI "uint32_t \fBsectors_per_fat\fP"
.br
.ti -1c
.RI "uint32_t \fBbytes_per_sector\fP"
.br
.ti -1c
.RI "uint32_t \fBsectors_per_cluster\fP"
.br
.ti -1c
.RI "uint32_t \fBfat_start\fP"
.br
.ti -1c
.RI "uint16_t \fBreserved_sector_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB83\fP of file \fBfat32\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t bytes_per_sector"

.PP
Definition at line \fB87\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t fat_start"

.PP
Definition at line \fB89\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t first_data_sector"

.PP
Definition at line \fB84\fP of file \fBfat32\&.h\fP\&.
.SS "uint16_t reserved_sector_count"

.PP
Definition at line \fB90\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t root_cluster"

.PP
Definition at line \fB85\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t sectors_per_cluster"

.PP
Definition at line \fB88\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t sectors_per_fat"

.PP
Definition at line \fB86\fP of file \fBfat32\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
