.TH "_GOP_PARAMS" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GOP_PARAMS
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <uefi_memory\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBFrameBufferBase\fP"
.br
.ti -1c
.RI "uint64_t \fBFrameBufferSize\fP"
.br
.ti -1c
.RI "uint32_t \fBWidth\fP"
.br
.ti -1c
.RI "uint32_t \fBHeight\fP"
.br
.ti -1c
.RI "uint32_t \fBPixelsPerScanLine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBuefi_memory\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t FrameBufferBase"

.PP
Definition at line \fB25\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint64_t FrameBufferSize"

.PP
Definition at line \fB26\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint32_t Height"

.PP
Definition at line \fB28\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint32_t PixelsPerScanLine"

.PP
Definition at line \fB29\fP of file \fBuefi_memory\&.h\fP\&.
.SS "uint32_t Width"

.PP
Definition at line \fB27\fP of file \fBuefi_memory\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
