.TH "_HBA_PRDT_ENTRY" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HBA_PRDT_ENTRY \- Physical Region Descriptor Table Entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ahci\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBdba\fP"
.br
.ti -1c
.RI "uint32_t \fBdbau\fP"
.br
.ti -1c
.RI "uint32_t \fBrsv0\fP"
.br
.ti -1c
.RI "uint32_t \fBdbc\fP: 22"
.br
.ti -1c
.RI "uint32_t \fBrsv1\fP: 9"
.br
.ti -1c
.RI "uint32_t \fBi\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Physical Region Descriptor Table Entry\&. 
.PP
Definition at line \fB98\fP of file \fBahci\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t dba"

.PP
Definition at line \fB99\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t dbau"

.PP
Definition at line \fB100\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t dbc"

.PP
Definition at line \fB104\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t i"

.PP
Definition at line \fB106\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t rsv0"

.PP
Definition at line \fB101\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t rsv1"

.PP
Definition at line \fB105\fP of file \fBahci\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
