.TH "_HBA_CMD_HEADER" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HBA_CMD_HEADER \- HBA Command Header (defines an AHCI Command)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ahci\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile uint32_t \fBdw0\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBprdbc\fP"
.br
.ti -1c
.RI "uint32_t \fBctba\fP"
.br
.ti -1c
.RI "uint32_t \fBctbau\fP"
.br
.ti -1c
.RI "uint32_t \fBrsv1\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
HBA Command Header (defines an AHCI Command) 
.PP
Definition at line \fB128\fP of file \fBahci\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t ctba"

.PP
Definition at line \fB131\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t ctbau"

.PP
Definition at line \fB132\fP of file \fBahci\&.h\fP\&.
.SS "volatile uint32_t dw0"

.PP
Definition at line \fB129\fP of file \fBahci\&.h\fP\&.
.SS "volatile uint32_t prdbc"

.PP
Definition at line \fB130\fP of file \fBahci\&.h\fP\&.
.SS "uint32_t rsv1[4]"

.PP
Definition at line \fB133\fP of file \fBahci\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
