.TH "_Queue" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Queue
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cpu_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBThread\fP * \fBhead\fP"
.br
.ti -1c
.RI "\fBThread\fP * \fBtail\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB78\fP of file \fBcpu_types\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBThread\fP* head"

.PP
Definition at line \fB79\fP of file \fBcpu_types\&.h\fP\&.
.SS "\fBThread\fP* tail"

.PP
Definition at line \fB80\fP of file \fBcpu_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
