.TH "_SPINLOCK" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SPINLOCK
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cpu_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "atomic_flag \fBLOCKED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB51\fP of file \fBcpu_types\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "atomic_flag LOCKED"

.PP
Definition at line \fB52\fP of file \fBcpu_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
