.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/memory/allocator/allocator.c" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/memory/allocator/allocator.c
.SH SYNOPSIS
.br
.PP
\fR#include 'allocator\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./bugcheck/bugcheck\&.h'\fP
.br
\fR#include '\&.\&./memory\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBframe_bitmap_init\fP (void)"
.br
.ti -1c
.RI "uintptr_t \fBalloc_frame\fP (void)"
.br
.ti -1c
.RI "void \fBfree_frame\fP (uintptr_t p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uintptr_t alloc_frame (void )"
Removed reserved pages use, for safeguarding against memory corruption within the kernel\&.
.PP
Definition at line \fB133\fP of file \fBallocator\&.c\fP\&.
.SS "void frame_bitmap_init (void )"

.PP
Definition at line \fB61\fP of file \fBallocator\&.c\fP\&.
.SS "void free_frame (uintptr_t p)"

.PP
Definition at line \fB149\fP of file \fBallocator\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
