.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/apic/apic.c" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/apic/apic.c
.SH SYNOPSIS
.br
.PP
\fR#include 'apic\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include '\&.\&./\&.\&./memory/paging/paging\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./memory/allocator/allocator\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIA32_APIC_BASE_MSR\fP   0x1BULL"
.br
.ti -1c
.RI "#define \fBAPIC_BASE_RESERVED\fP   0xFFF0000000000000ULL"
.br
.ti -1c
.RI "#define \fBLAPIC_PAGE_SIZE\fP   0x1000"
.br
.ti -1c
.RI "#define \fBLAPIC_MAP_FLAGS\fP   (\fBPAGE_PRESENT\fP | \fBPAGE_RW\fP | \fBPAGE_PCD\fP)"
.br
.ti -1c
.RI "#define \fBLAPIC_DEFAULT_PADDR\fP   0xFEE00000ULL"
.br
.ti -1c
.RI "#define \fBAPIC_LVT_TIMER_PERIODIC\fP   (1U << 17)"
.br
.ti -1c
.RI "#define \fBAPIC_TIMER_MASKED\fP   (1U << 16)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBLAPIC_ID\fP = 0x020, \fBLAPIC_VERSION\fP = 0x030, \fBLAPIC_TPR\fP = 0x080, \fBLAPIC_EOI\fP = 0x0B0, \fBLAPIC_SVR\fP = 0x0F0, \fBLAPIC_ESR\fP = 0x280, \fBLAPIC_ICR_LOW\fP = 0x300, \fBLAPIC_ICR_HIGH\fP = 0x310, \fBLAPIC_LVT_TIMER\fP = 0x320, \fBLAPIC_LVT_THERMAL\fP = 0x330, \fBLAPIC_LVT_PCC\fP = 0x340, \fBLAPIC_LVT_LINT0\fP = 0x350, \fBLAPIC_LVT_LINT1\fP = 0x360, \fBLAPIC_LVT_ERROR\fP = 0x370, \fBLAPIC_TIMER_INITCNT\fP = 0x380, \fBLAPIC_TIMER_CURRCNT\fP = 0x390, \fBLAPIC_TIMER_DIV\fP = 0x3E0 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlapic_write\fP (uint32_t reg, uint32_t value)"
.br
.ti -1c
.RI "void \fBlapic_init_siv\fP ()"
.br
.ti -1c
.RI "void \fBlapic_enable\fP (void)"
.br
.ti -1c
.RI "void \fBlapic_init_bsp\fP (void)"
.br
.ti -1c
.RI "void \fBlapic_send_ipi\fP (uint8_t apic_id, uint8_t vector, uint32_t flags)"
.br
.ti -1c
.RI "void \fBlapic_eoi\fP (void)"
.br
.ti -1c
.RI "int \fBinit_lapic_timer\fP (uint32_t hz)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define APIC_BASE_RESERVED   0xFFF0000000000000ULL"

.PP
Definition at line \fB8\fP of file \fBapic\&.c\fP\&.
.SS "#define APIC_LVT_TIMER_PERIODIC   (1U << 17)"

.PP
Definition at line \fB140\fP of file \fBapic\&.c\fP\&.
.SS "#define APIC_TIMER_MASKED   (1U << 16)"

.PP
Definition at line \fB141\fP of file \fBapic\&.c\fP\&.
.SS "#define IA32_APIC_BASE_MSR   0x1BULL"

.PP
Definition at line \fB7\fP of file \fBapic\&.c\fP\&.
.SS "#define LAPIC_DEFAULT_PADDR   0xFEE00000ULL"

.PP
Definition at line \fB35\fP of file \fBapic\&.c\fP\&.
.SS "#define LAPIC_MAP_FLAGS   (\fBPAGE_PRESENT\fP | \fBPAGE_RW\fP | \fBPAGE_PCD\fP)"

.PP
Definition at line \fB11\fP of file \fBapic\&.c\fP\&.
.SS "#define LAPIC_PAGE_SIZE   0x1000"

.PP
Definition at line \fB10\fP of file \fBapic\&.c\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILAPIC_ID \fP
.TP
\f(BILAPIC_VERSION \fP
.TP
\f(BILAPIC_TPR \fP
.TP
\f(BILAPIC_EOI \fP
.TP
\f(BILAPIC_SVR \fP
.TP
\f(BILAPIC_ESR \fP
.TP
\f(BILAPIC_ICR_LOW \fP
.TP
\f(BILAPIC_ICR_HIGH \fP
.TP
\f(BILAPIC_LVT_TIMER \fP
.TP
\f(BILAPIC_LVT_THERMAL \fP
.TP
\f(BILAPIC_LVT_PCC \fP
.TP
\f(BILAPIC_LVT_LINT0 \fP
.TP
\f(BILAPIC_LVT_LINT1 \fP
.TP
\f(BILAPIC_LVT_ERROR \fP
.TP
\f(BILAPIC_TIMER_INITCNT \fP
.TP
\f(BILAPIC_TIMER_CURRCNT \fP
.TP
\f(BILAPIC_TIMER_DIV \fP
.PP
Definition at line \fB14\fP of file \fBapic\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int init_lapic_timer (uint32_t hz)"

.PP
Definition at line \fB158\fP of file \fBapic\&.c\fP\&.
.SS "void lapic_enable (void )"

.PP
Definition at line \fB84\fP of file \fBapic\&.c\fP\&.
.SS "void lapic_eoi (void )"

.PP
Definition at line \fB127\fP of file \fBapic\&.c\fP\&.
.SS "void lapic_init_bsp (void )"

.PP
Definition at line \fB103\fP of file \fBapic\&.c\fP\&.
.SS "void lapic_init_siv ()"

.PP
Definition at line \fB62\fP of file \fBapic\&.c\fP\&.
.SS "void lapic_send_ipi (uint8_t apic_id, uint8_t vector, uint32_t flags)"

.PP
Definition at line \fB120\fP of file \fBapic\&.c\fP\&.
.SS "void lapic_write (uint32_t reg, uint32_t value)"

.PP
Definition at line \fB57\fP of file \fBapic\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
