.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/assert.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/assert.h
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include 'bugcheck/bugcheck\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBassert\fP(\&.\&.\&.)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define assert( \&.\&.\&.)"
\fBValue:\fP
.nf
do { } while(0)
.PP
.fi

.PP
Definition at line \fB54\fP of file \fBassert\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
