.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/intrin/atomic.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/intrin/atomic.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
