.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/bugcheck/bugcheck.c" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/bugcheck/bugcheck.c
.SH SYNOPSIS
.br
.PP
\fR#include 'bugcheck\&.h'\fP
.br
\fR#include '\&.\&./trace\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNOTHING\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((noreturn))"
.br
.ti -1c
.RI "void \fBMtBugcheckEx\fP (\fBCTX_FRAME\fP *context, \fBINT_FRAME\fP *\fBint_frame\fP, \fBBUGCHECK_CODES\fP \fBerr_code\fP, \fBBUGCHECK_ADDITIONALS\fP *\fBadditional\fP, bool \fBisAdditionals\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGOP_PARAMS\fP \fBgop_local\fP"
.br
.ti -1c
.RI "\fBLASTFUNC_HISTORY\fP \fBlastfunc_history\fP"
.br
.ti -1c
.RI "bool \fBisBugChecking\fP"
.br
.ti -1c
.RI "\fBCPU\fP \fBcpu\fP"
.br
.ti -1c
.RI "uint32_t \fBcursor_x\fP"
.br
.ti -1c
.RI "uint32_t \fBcursor_y\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NOTHING"

.PP
Definition at line \fB11\fP of file \fBbugcheck\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "__attribute__ ((noreturn) )"

.PP
Definition at line \fB212\fP of file \fBbugcheck\&.c\fP\&.
.SS "void MtBugcheckEx (\fBCTX_FRAME\fP * context, \fBINT_FRAME\fP * int_frame, \fBBUGCHECK_CODES\fP err_code, \fBBUGCHECK_ADDITIONALS\fP * additional, bool isAdditionals)"

.PP
Definition at line \fB322\fP of file \fBbugcheck\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCPU\fP cpu\fR [extern]\fP"

.PP
Definition at line \fB23\fP of file \fBkernel\&.c\fP\&.
.SS "uint32_t cursor_x\fR [extern]\fP"

.PP
Definition at line \fB12\fP of file \fBgop\&.c\fP\&.
.SS "uint32_t cursor_y\fR [extern]\fP"

.PP
Definition at line \fB12\fP of file \fBgop\&.c\fP\&.
.SS "\fBGOP_PARAMS\fP gop_local\fR [extern]\fP"

.PP
Definition at line \fB155\fP of file \fBgop\&.c\fP\&.
.SS "bool isBugChecking\fR [extern]\fP"

.PP
Definition at line \fB21\fP of file \fBkernel\&.c\fP\&.
.SS "\fBLASTFUNC_HISTORY\fP lastfunc_history\fR [extern]\fP"

.PP
Definition at line \fB22\fP of file \fBkernel\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
