.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/spinlock Directory Reference" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/spinlock Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBspinlock\&.h\fP"
.br
.in -1c
