.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu Directory Reference" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBapic\fP"
.br
.ti -1c
.RI "directory \fBcpuid\fP"
.br
.ti -1c
.RI "directory \fBdpc\fP"
.br
.ti -1c
.RI "directory \fBirql\fP"
.br
.ti -1c
.RI "directory \fBscheduler\fP"
.br
.ti -1c
.RI "directory \fBspinlock\fP"
.br
.ti -1c
.RI "directory \fBthread\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcpu\&.h\fP"
.br
.ti -1c
.RI "file \fBcpu_types\&.h\fP"
.br
.in -1c
