.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/memory Directory Reference" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/memory Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBallocator\fP"
.br
.ti -1c
.RI "directory \fBpaging\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmemory\&.c\fP"
.br
.ti -1c
.RI "file \fBmemory\&.h\fP"
.br
.in -1c
