.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/drivers/gop/font8x16.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/drivers/gop/font8x16.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBfont8x16\fP [256][16]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t font8x16[256][16]\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
