.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/drivers/gop/gop.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/drivers/gop/gop.h
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include '\&.\&./\&.\&./defs/stdarg_myos\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./trace\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./memory/memory\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./memory/allocator/uefi_memory\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOLOR_RED\fP   0xFFFF0000"
.br
.RI "Colors definitions for easier access\&. "
.ti -1c
.RI "#define \fBCOLOR_GREEN\fP   0xFF00FF00"
.br
.ti -1c
.RI "#define \fBCOLOR_BLUE\fP   0xFF0000FF"
.br
.ti -1c
.RI "#define \fBCOLOR_WHITE\fP   0xFFFFFFFF"
.br
.ti -1c
.RI "#define \fBCOLOR_BLACK\fP   0xFF000000"
.br
.ti -1c
.RI "#define \fBCOLOR_YELLOW\fP   0xFFFFFF00"
.br
.ti -1c
.RI "#define \fBCOLOR_CYAN\fP   0xFF00FFFF"
.br
.ti -1c
.RI "#define \fBCOLOR_MAGENTA\fP   0xFFFF00FF"
.br
.ti -1c
.RI "#define \fBCOLOR_GRAY\fP   0xFF808080"
.br
.ti -1c
.RI "#define \fBCOLOR_DARK_GRAY\fP   0xFF404040"
.br
.ti -1c
.RI "#define \fBCOLOR_LIGHT_GRAY\fP   0xFFD3D3D3"
.br
.ti -1c
.RI "#define \fBCOLOR_ORANGE\fP   0xFFFFA500"
.br
.ti -1c
.RI "#define \fBCOLOR_BROWN\fP   0xFFA52A2A"
.br
.ti -1c
.RI "#define \fBCOLOR_PURPLE\fP   0xFF800080"
.br
.ti -1c
.RI "#define \fBCOLOR_PINK\fP   0xFFFFC0CB"
.br
.ti -1c
.RI "#define \fBCOLOR_LIME\fP   0xFF32CD32"
.br
.ti -1c
.RI "#define \fBCOLOR_NAVY\fP   0xFF000080"
.br
.ti -1c
.RI "#define \fBCOLOR_TEAL\fP   0xFF008080"
.br
.ti -1c
.RI "#define \fBCOLOR_OLIVE\fP   0xFF808000"
.br
.ti -1c
.RI "#define \fBFONT_SCALE\fP   1"
.br
.ti -1c
.RI "#define \fBgop_printf_forced\fP(color,  fmt, \&.\&.\&.)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdraw_char\fP (\fBGOP_PARAMS\fP *gop, char c, uint32_t x, uint32_t y, uint32_t color)"
.br
.ti -1c
.RI "void \fBdraw_string\fP (\fBGOP_PARAMS\fP *gop, const char *s, uint32_t x, uint32_t y, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_printf\fP (uint32_t color, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBgop_put_char\fP (\fBGOP_PARAMS\fP *gop, char c, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_puts\fP (\fBGOP_PARAMS\fP *gop, const char *s, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_scroll\fP (\fBGOP_PARAMS\fP *gop)"
.br
.ti -1c
.RI "void \fBgop_clear_screen\fP (\fBGOP_PARAMS\fP *gop, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_print_dec\fP (\fBGOP_PARAMS\fP *gop, unsigned val, uint32_t color)"
.br
.ti -1c
.RI "void \fBgop_print_hex\fP (\fBGOP_PARAMS\fP *gop, uint64_t val, uint32_t color)"
.br
.ti -1c
.RI "int \fBksnprintf\fP (char *buf, size_t bufsize, const char *fmt,\&.\&.\&.)"
.br
.RI "snprintf equivalent\&. -- Safe to run at ANY \fBIRQL\fP\&. "
.ti -1c
.RI "int \fBkstrcmp\fP (const char *s1, const char *s2)"
.br
.ti -1c
.RI "size_t \fBkstrlen\fP (const char *str)"
.br
.ti -1c
.RI "char * \fBkstrcpy\fP (char *dst, const char *src)"
.br
.ti -1c
.RI "char * \fBkstrtok\fP (char *str, const char *delim)"
.br
.ti -1c
.RI "char * \fBkstrncat\fP (char *dest, const char *src, size_t max_len)"
.br
.RI "Concatenates src onto dest, up to max_len total bytes in dest\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLOR_BLACK   0xFF000000"

.PP
Definition at line \fB15\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_BLUE   0xFF0000FF"

.PP
Definition at line \fB13\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_BROWN   0xFFA52A2A"

.PP
Definition at line \fB23\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_CYAN   0xFF00FFFF"

.PP
Definition at line \fB17\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_DARK_GRAY   0xFF404040"

.PP
Definition at line \fB20\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_GRAY   0xFF808080"

.PP
Definition at line \fB19\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_GREEN   0xFF00FF00"

.PP
Definition at line \fB12\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_LIGHT_GRAY   0xFFD3D3D3"

.PP
Definition at line \fB21\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_LIME   0xFF32CD32"

.PP
Definition at line \fB26\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_MAGENTA   0xFFFF00FF"

.PP
Definition at line \fB18\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_NAVY   0xFF000080"

.PP
Definition at line \fB27\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_OLIVE   0xFF808000"

.PP
Definition at line \fB29\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_ORANGE   0xFFFFA500"

.PP
Definition at line \fB22\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_PINK   0xFFFFC0CB"

.PP
Definition at line \fB25\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_PURPLE   0xFF800080"

.PP
Definition at line \fB24\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_RED   0xFFFF0000"

.PP
Colors definitions for easier access\&. 
.PP
Definition at line \fB11\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_TEAL   0xFF008080"

.PP
Definition at line \fB28\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_WHITE   0xFFFFFFFF"

.PP
Definition at line \fB14\fP of file \fBgop\&.h\fP\&.
.SS "#define COLOR_YELLOW   0xFFFFFF00"

.PP
Definition at line \fB16\fP of file \fBgop\&.h\fP\&.
.SS "#define FONT_SCALE   1"

.PP
Definition at line \fB41\fP of file \fBgop\&.h\fP\&.
.SS "#define gop_printf_forced( color,  fmt,  \&.\&.\&.)"
\fBValue:\fP
.nf
gop_printf(color, fmt, ##__VA_ARGS__)
.PP
.fi

.PP
Definition at line \fB57\fP of file \fBgop\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void draw_char (\fBGOP_PARAMS\fP * gop, char c, uint32_t x, uint32_t y, uint32_t color)"

.PP
Definition at line \fB15\fP of file \fBgop\&.c\fP\&.
.SS "void draw_string (\fBGOP_PARAMS\fP * gop, const char * s, uint32_t x, uint32_t y, uint32_t color)"

.PP
Definition at line \fB50\fP of file \fBgop\&.c\fP\&.
.SS "void gop_clear_screen (\fBGOP_PARAMS\fP * gop, uint32_t color)"

.PP
Definition at line \fB157\fP of file \fBgop\&.c\fP\&.
.SS "void gop_print_dec (\fBGOP_PARAMS\fP * gop, unsigned val, uint32_t color)"

.PP
Definition at line \fB139\fP of file \fBgop\&.c\fP\&.
.SS "void gop_print_hex (\fBGOP_PARAMS\fP * gop, uint64_t val, uint32_t color)"

.PP
Definition at line \fB145\fP of file \fBgop\&.c\fP\&.
.SS "void gop_printf (uint32_t color, const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB398\fP of file \fBgop\&.c\fP\&.
.SS "void gop_put_char (\fBGOP_PARAMS\fP * gop, char c, uint32_t color)"

.PP
Definition at line \fB78\fP of file \fBgop\&.c\fP\&.
.SS "void gop_puts (\fBGOP_PARAMS\fP * gop, const char * s, uint32_t color)"

.PP
Definition at line \fB119\fP of file \fBgop\&.c\fP\&.
.SS "void gop_scroll (\fBGOP_PARAMS\fP * gop)"

.PP
Definition at line \fB58\fP of file \fBgop\&.c\fP\&.
.SS "int ksnprintf (char * buf, size_t bufsize, const char * fmt,  \&.\&.\&.)"

.PP
snprintf equivalent\&. -- Safe to run at ANY \fBIRQL\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuf\fP Buffer to format\&.
.br
\fIbufSize\fP Size of the buffer\&.
.br
\fIfmt\fP String and format\&.
.RE
.PP
<return>Amount of bytes written\&. (excluding null terminator)</return> 
.PP
Definition at line \fB323\fP of file \fBgop\&.c\fP\&.
.SS "int kstrcmp (const char * s1, const char * s2)"

.PP
Definition at line \fB389\fP of file \fBgop\&.c\fP\&.
.SS "char * kstrcpy (char * dst, const char * src)"

.PP
Definition at line \fB273\fP of file \fBgop\&.c\fP\&.
.SS "size_t kstrlen (const char * str)"

.PP
Definition at line \fB262\fP of file \fBgop\&.c\fP\&.
.SS "char * kstrncat (char * dest, const char * src, size_t max_len)"

.PP
Concatenates src onto dest, up to max_len total bytes in dest\&. 
.PP
\fBParameters\fP
.RS 4
\fIdest\fP Destination buffer (must be mutable)
.br
\fIsrc\fP String to append
.br
\fImax_len\fP Total size of the destination buffer
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to dest
.RE
.PP

.PP
Definition at line \fB234\fP of file \fBgop\&.c\fP\&.
.SS "char * kstrtok (char * str, const char * delim)"

.PP
Definition at line \fB286\fP of file \fBgop\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
