.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/intrin/intrin.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/intrin/intrin.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPIC1_COMMAND_MASTER\fP   0x20"
.br
.ti -1c
.RI "#define \fBPIC1_DATA\fP   0x21"
.br
.ti -1c
.RI "#define \fBPIC2_COMMAND_SLAVE\fP   0xA0"
.br
.ti -1c
.RI "#define \fBPIC2_DATA\fP   0xA1"
.br
.ti -1c
.RI "#define \fBPIC_EOI\fP   0x20"
.br
.ti -1c
.RI "#define \fBUNREFERENCED_PARAMETER\fP(x)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PIC1_COMMAND_MASTER   0x20"

.PP
Definition at line \fB10\fP of file \fBintrin\&.h\fP\&.
.SS "#define PIC1_DATA   0x21"

.PP
Definition at line \fB11\fP of file \fBintrin\&.h\fP\&.
.SS "#define PIC2_COMMAND_SLAVE   0xA0"

.PP
Definition at line \fB12\fP of file \fBintrin\&.h\fP\&.
.SS "#define PIC2_DATA   0xA1"

.PP
Definition at line \fB13\fP of file \fBintrin\&.h\fP\&.
.SS "#define PIC_EOI   0x20"

.PP
Definition at line \fB16\fP of file \fBintrin\&.h\fP\&.
.SS "#define UNREFERENCED_PARAMETER( x)"
\fBValue:\fP
.nf
(void)(x)
.PP
.fi

.PP
Definition at line \fB19\fP of file \fBintrin\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
