.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/kernel.c" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/kernel.c
.SH SYNOPSIS
.br
.PP
\fR#include 'kernel\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_AHCI_CONTROLLERS\fP   32"
.br
.ti -1c
.RI "#define \fBMAX_MEMORY_MAP_SIZE\fP   0x4000"
.br
.ti -1c
.RI "#define \fBISRAEL_UTC_OFFSET\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcopy_memory_map\fP (\fBBOOT_INFO\fP *boot_info)"
.br
.ti -1c
.RI "void \fBcopy_gop\fP (\fBBOOT_INFO\fP *boot_info)"
.br
.ti -1c
.RI "void \fBinit_boot_info\fP (\fBBOOT_INFO\fP *boot_info)"
.br
.ti -1c
.RI "void \fBInitCPU\fP (void)"
.br
.ti -1c
.RI "void \fBkernel_idle_checks\fP (void)"
.br
.ti -1c
.RI "void \fBkernel_main\fP (\fBBOOT_INFO\fP *boot_info)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint64_t \fBahci_bases_local\fP [\fBMAX_AHCI_CONTROLLERS\fP]"
.br
.ti -1c
.RI "\fBGOP_PARAMS\fP \fBgop_local\fP"
.br
.ti -1c
.RI "\fBBOOT_INFO\fP \fBboot_info_local\fP"
.br
.ti -1c
.RI "bool \fBisBugChecking\fP = false"
.br
.ti -1c
.RI "\fBLASTFUNC_HISTORY\fP \fBlastfunc_history\fP = { \&.current_index = \-1 }"
.br
.ti -1c
.RI "\fBCPU\fP \fBcpu\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ISRAEL_UTC_OFFSET   3"

.SS "#define MAX_AHCI_CONTROLLERS   32"

.PP
Definition at line \fB12\fP of file \fBkernel\&.c\fP\&.
.SS "#define MAX_MEMORY_MAP_SIZE   0x4000"

.PP
Definition at line \fB29\fP of file \fBkernel\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void copy_gop (\fBBOOT_INFO\fP * boot_info)"

.PP
Definition at line \fB49\fP of file \fBkernel\&.c\fP\&.
.SS "void copy_memory_map (\fBBOOT_INFO\fP * boot_info)"

.PP
Definition at line \fB33\fP of file \fBkernel\&.c\fP\&.
.SS "void init_boot_info (\fBBOOT_INFO\fP * boot_info)"

.PP
Definition at line \fB61\fP of file \fBkernel\&.c\fP\&.
.SS "void InitCPU (void )"

.PP
Definition at line \fB94\fP of file \fBkernel\&.c\fP\&.
.SS "void kernel_idle_checks (void )"

.PP
Definition at line \fB107\fP of file \fBkernel\&.c\fP\&.
.SS "void kernel_main (\fBBOOT_INFO\fP * boot_info)"
Remember that paging is on when this is called, as UEFI turned it on\&. 
.PP
Definition at line \fB153\fP of file \fBkernel\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint64_t ahci_bases_local[\fBMAX_AHCI_CONTROLLERS\fP]"

.PP
Definition at line \fB13\fP of file \fBkernel\&.c\fP\&.
.SS "\fBBOOT_INFO\fP boot_info_local"

.PP
Definition at line \fB16\fP of file \fBkernel\&.c\fP\&.
.SS "\fBCPU\fP cpu"

.PP
Definition at line \fB23\fP of file \fBkernel\&.c\fP\&.
.SS "\fBGOP_PARAMS\fP gop_local"

.PP
Definition at line \fB15\fP of file \fBkernel\&.c\fP\&.
.SS "bool isBugChecking = false"

.PP
Definition at line \fB21\fP of file \fBkernel\&.c\fP\&.
.SS "\fBLASTFUNC_HISTORY\fP lastfunc_history = { \&.current_index = \-1 }"

.PP
Definition at line \fB22\fP of file \fBkernel\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
