.TH "LASTFUNC_HISTORY" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LASTFUNC_HISTORY
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <trace\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBnames\fP [\fBLASTFUNC_HISTORY_SIZE\fP][\fBLASTFUNC_BUFFER_SIZE\fP]"
.br
.ti -1c
.RI "int \fBcurrent_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBtrace\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int current_index"

.PP
Definition at line \fB15\fP of file \fBtrace\&.h\fP\&.
.SS "uint8_t names[\fBLASTFUNC_HISTORY_SIZE\fP][\fBLASTFUNC_BUFFER_SIZE\fP]"

.PP
Definition at line \fB14\fP of file \fBtrace\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
