.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/interrupts/handlers/scancodes.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/interrupts/handlers/scancodes.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_3\fP   0x04"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_7\fP   0x08"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_MINUS\fP   0x0C"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_Q\fP   0x10"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_T\fP   0x14"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_O\fP   0x18"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_ENTER\fP   0x1C"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_D\fP   0x20"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_J\fP   0x24"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_SINGLEQUOTE\fP   0x28"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_Z\fP   0x2C"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_B\fP   0x30"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_LEFT_SHIFT\fP   0x2A"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_DOT\fP   0x34"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_LEFT_ALT\fP   0x38"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_LEFT_CONTROL\fP   0x1D"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_PRESSED_CAPS_LOCK\fP   0x3A"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_UP\fP   0x48"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_LEFT\fP   0x4B"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_DOWN\fP   0x50"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_RIGHT\fP   0x4D"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_RELEASE_LEFT_CONTROL\fP   0x9D"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_RELEASE_LEFT_SHIFT\fP   0xAA"
.br
.ti -1c
.RI "#define \fBKEYBOARD_SCANCODE_RELEASE_CAPS_LOCK\fP   0xBB"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBscancode_to_ascii\fP []"
.br
.ti -1c
.RI "char \fBscancode_to_ascii_shift\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_DOWN   0x50"

.PP
Definition at line \fB33\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_LEFT   0x4B"

.PP
Definition at line \fB32\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_RIGHT   0x4D"

.PP
Definition at line \fB34\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_EXTENDED_PRESSED_CURSOR_UP   0x48"

.PP
Definition at line \fB31\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_3   0x04"

.PP
Definition at line \fB12\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_7   0x08"

.PP
Definition at line \fB13\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_B   0x30"

.PP
Definition at line \fB23\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_CAPS_LOCK   0x3A"

.PP
Definition at line \fB28\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_D   0x20"

.PP
Definition at line \fB19\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_DOT   0x34"

.PP
Definition at line \fB25\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_ENTER   0x1C"

.PP
Definition at line \fB18\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_J   0x24"

.PP
Definition at line \fB20\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_LEFT_ALT   0x38"

.PP
Definition at line \fB26\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_LEFT_CONTROL   0x1D"

.PP
Definition at line \fB27\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_LEFT_SHIFT   0x2A"

.PP
Definition at line \fB24\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_MINUS   0x0C"

.PP
Definition at line \fB14\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_O   0x18"

.PP
Definition at line \fB17\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_Q   0x10"

.PP
Definition at line \fB15\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_SINGLEQUOTE   0x28"

.PP
Definition at line \fB21\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_T   0x14"

.PP
Definition at line \fB16\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_PRESSED_Z   0x2C"

.PP
Definition at line \fB22\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_RELEASE_CAPS_LOCK   0xBB"

.PP
Definition at line \fB39\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_RELEASE_LEFT_CONTROL   0x9D"

.PP
Definition at line \fB37\fP of file \fBscancodes\&.h\fP\&.
.SS "#define KEYBOARD_SCANCODE_RELEASE_LEFT_SHIFT   0xAA"

.PP
Definition at line \fB38\fP of file \fBscancodes\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char scancode_to_ascii[]"
\fBInitial value:\fP
.nf
= {
    0,  27, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '\-', '=', '\\b',
    '\\t', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\n',
    0, 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\\'', '`',
    0, '\\\\', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '\&.', '/', 0,
    '*', 0, ' '
}
.PP
.fi

.PP
Definition at line \fB41\fP of file \fBscancodes\&.h\fP\&.
.SS "char scancode_to_ascii_shift[]"
\fBInitial value:\fP
.nf
= {
    0,  27, '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '\\b',
    '\\t', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '\\n',
    0, 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', '~',
    0, '|', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?', 0,
    '*', 0, ' '
}
.PP
.fi

.PP
Definition at line \fB49\fP of file \fBscancodes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
