.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/scheduler/scheduler.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/scheduler/scheduler.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./cpu\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./memory/memory\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_TIMESLICE\fP   1"
.br
.ti -1c
.RI "#define \fBKERNEL_CS\fP   0x08"
.br
.ti -1c
.RI "#define \fBKERNEL_DS\fP   0x10"
.br
.ti -1c
.RI "#define \fBKERNEL_SS\fP   0x10"
.br
.ti -1c
.RI "#define \fBUSER_CS\fP   0x18"
.br
.ti -1c
.RI "#define \fBUSER_DS\fP   0x20"
.br
.ti -1c
.RI "#define \fBUSER_SS\fP   0x20"
.br
.ti -1c
.RI "#define \fBINITIAL_RFLAGS\fP   0x202"
.br
.ti -1c
.RI "#define \fBUSER_RFLAGS\fP   0x246"
.br
.ti -1c
.RI "#define \fBYield\fP()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBInitScheduler\fP (void)"
.br
.ti -1c
.RI "void \fBSchedule\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCPU\fP \fBcpu\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_TIMESLICE   1"

.PP
Definition at line \fB15\fP of file \fBscheduler\&.h\fP\&.
.SS "#define INITIAL_RFLAGS   0x202"

.PP
Definition at line \fB23\fP of file \fBscheduler\&.h\fP\&.
.SS "#define KERNEL_CS   0x08"

.PP
Definition at line \fB17\fP of file \fBscheduler\&.h\fP\&.
.SS "#define KERNEL_DS   0x10"

.PP
Definition at line \fB18\fP of file \fBscheduler\&.h\fP\&.
.SS "#define KERNEL_SS   0x10"

.PP
Definition at line \fB19\fP of file \fBscheduler\&.h\fP\&.
.SS "#define USER_CS   0x18"

.PP
Definition at line \fB20\fP of file \fBscheduler\&.h\fP\&.
.SS "#define USER_DS   0x20"

.PP
Definition at line \fB21\fP of file \fBscheduler\&.h\fP\&.
.SS "#define USER_RFLAGS   0x246"

.PP
Definition at line \fB24\fP of file \fBscheduler\&.h\fP\&.
.SS "#define USER_SS   0x20"

.PP
Definition at line \fB22\fP of file \fBscheduler\&.h\fP\&.
.SS "#define Yield()"
\fBValue:\fP
.nf
Schedule()
.PP
.fi

.PP
Definition at line \fB33\fP of file \fBscheduler\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void InitScheduler (void )"

.PP
Definition at line \fB23\fP of file \fBscheduler\&.c\fP\&.
.SS "void Schedule (void )"

.PP
Definition at line \fB63\fP of file \fBscheduler\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCPU\fP cpu\fR [extern]\fP"

.PP
Definition at line \fB23\fP of file \fBkernel\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
