.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/spinlock/spinlock.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/cpu/spinlock/spinlock.h
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
