.TH "C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/defs/stdarg_myos.h" 3 "MatanelOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matanel/Desktop/Projects/KernelDevelopment/kernel/defs/stdarg_myos.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBva_start\fP(ap,  last)"
.br
.ti -1c
.RI "#define \fBva_arg\fP(ap,  type)"
.br
.ti -1c
.RI "#define \fBva_end\fP(ap)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef __builtin_va_list \fBva_list\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define va_arg( ap,  type)"
\fBValue:\fP
.nf
__builtin_va_arg(ap, type)
.PP
.fi

.PP
Definition at line \fB12\fP of file \fBstdarg_myos\&.h\fP\&.
.SS "#define va_end( ap)"
\fBValue:\fP
.nf
__builtin_va_end(ap)
.PP
.fi

.PP
Definition at line \fB13\fP of file \fBstdarg_myos\&.h\fP\&.
.SS "#define va_start( ap,  last)"
\fBValue:\fP
.nf
__builtin_va_start(ap, last)
.PP
.fi

.PP
Definition at line \fB11\fP of file \fBstdarg_myos\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef __builtin_va_list \fBva_list\fP"

.PP
Definition at line \fB9\fP of file \fBstdarg_myos\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MatanelOS from the source code\&.
