#ifndef MATANELOS_USERMODE_HEAP_TEST_H
#define MATANELOS_USERMODE_HEAP_TEST_H

#include "../../shared/include/mtstatus.h"

/* Test-only process exit statuses consumed by the kernel heap controller. */
#define MT_HEAP_TEST_NO_PROCESS_HEAP       ((MTSTATUS)0xCF100001L)
#define MT_HEAP_TEST_CREATE_FAILED         ((MTSTATUS)0xCF100002L)
#define MT_HEAP_TEST_SLAB_ALLOCATION       ((MTSTATUS)0xCF100003L)
#define MT_HEAP_TEST_SLAB_ALIGNMENT        ((MTSTATUS)0xCF100004L)
#define MT_HEAP_TEST_SLAB_ZEROING          ((MTSTATUS)0xCF100005L)
#define MT_HEAP_TEST_SLAB_FREE             ((MTSTATUS)0xCF100006L)
#define MT_HEAP_TEST_SLAB_DOUBLE_FREE      ((MTSTATUS)0xCF100007L)
#define MT_HEAP_TEST_SLAB_REUSE            ((MTSTATUS)0xCF100008L)
#define MT_HEAP_TEST_SEGMENT_ALLOCATION    ((MTSTATUS)0xCF100009L)
#define MT_HEAP_TEST_SEGMENT_ALIGNMENT     ((MTSTATUS)0xCF10000AL)
#define MT_HEAP_TEST_SEGMENT_ZEROING       ((MTSTATUS)0xCF10000BL)
#define MT_HEAP_TEST_SEGMENT_FREE          ((MTSTATUS)0xCF10000CL)
#define MT_HEAP_TEST_INVALID_FREE          ((MTSTATUS)0xCF10000DL)
#define MT_HEAP_TEST_SPLIT_REUSE           ((MTSTATUS)0xCF10000EL)
#define MT_HEAP_TEST_COALESCING             ((MTSTATUS)0xCF10000FL)
#define MT_HEAP_TEST_LARGE_GROWTH           ((MTSTATUS)0xCF100010L)
#define MT_HEAP_TEST_MAXIMUM_SIZE           ((MTSTATUS)0xCF100011L)
#define MT_HEAP_TEST_THREAD_CREATE          ((MTSTATUS)0xCF100012L)
#define MT_HEAP_TEST_THREAD_WAIT            ((MTSTATUS)0xCF100013L)
#define MT_HEAP_TEST_THREAD_CLOSE           ((MTSTATUS)0xCF100014L)
#define MT_HEAP_TEST_CONCURRENT_ALLOCATION  ((MTSTATUS)0xCF100015L)
#define MT_HEAP_TEST_CONCURRENT_FREE        ((MTSTATUS)0xCF100016L)
#define MT_HEAP_TEST_SLAB_EXCEPTION          ((MTSTATUS)0xCF100017L)
#define MT_HEAP_TEST_SEGMENT_EXCEPTION       ((MTSTATUS)0xCF100018L)
#define MT_HEAP_TEST_SPLIT_EXCEPTION         ((MTSTATUS)0xCF100019L)
#define MT_HEAP_TEST_MAXIMUM_EXCEPTION       ((MTSTATUS)0xCF10001AL)
#define MT_HEAP_TEST_CONCURRENT_EXCEPTION    ((MTSTATUS)0xCF10001BL)
#define MT_HEAP_TEST_DESTROY                  ((MTSTATUS)0xCF10001CL)
#define MT_HEAP_TEST_PROCESS_HEAP_DESTROY     ((MTSTATUS)0xCF10001DL)
#define MT_HEAP_TEST_DESTROY_EXCEPTION        ((MTSTATUS)0xCF10001EL)

#endif /* MATANELOS_USERMODE_HEAP_TEST_H */
