#ifndef MATANELOS_USERMODE_LOADER_TEST_H
#define MATANELOS_USERMODE_LOADER_TEST_H

#include "../../shared/include/mtapi.h"
#include "../../shared/include/mtstatus.h"

/* Test-only process exit statuses consumed by the kernel loader controller. */
#define MT_LOADER_TEST_LOAD_FAILED          ((MTSTATUS)0xCF200001L)
#define MT_LOADER_TEST_ENTRY_STATE          ((MTSTATUS)0xCF200002L)
#define MT_LOADER_TEST_REBASE               ((MTSTATUS)0xCF200003L)
#define MT_LOADER_TEST_EXPORT               ((MTSTATUS)0xCF200004L)
#define MT_LOADER_TEST_IMPORT_RELOCATION    ((MTSTATUS)0xCF200005L)
#define MT_LOADER_TEST_DUPLICATE_ENTRY      ((MTSTATUS)0xCF200006L)
#define MT_LOADER_TEST_DUPLICATE_REFERENCE  ((MTSTATUS)0xCF200007L)
#define MT_LOADER_TEST_ATTACH_REPEAT        ((MTSTATUS)0xCF200008L)
#define MT_LOADER_TEST_REJECT_STATUS        ((MTSTATUS)0xCF200009L)
#define MT_LOADER_TEST_REJECT_OUTPUT        ((MTSTATUS)0xCF20000AL)
#define MT_LOADER_TEST_REJECT_ROLLBACK      ((MTSTATUS)0xCF20000BL)
#define MT_LOADER_TEST_LAST_STATUS          ((MTSTATUS)0xCF20000CL)
#define MT_LOADER_TEST_LAST_ERROR           ((MTSTATUS)0xCF20000DL)
#define MT_LOADER_TEST_MODULE_HANDLE        ((MTSTATUS)0xCF20000EL)
#define MT_LOADER_TEST_MISSING_MODULE       ((MTSTATUS)0xCF20000FL)
#define MT_LOADER_TEST_MISSING_EXPORT       ((MTSTATUS)0xCF200010L)
#define MT_LOADER_TEST_INVALID_PARAMETER    ((MTSTATUS)0xCF200011L)

/* Test-only MTDLL entrypoint. It is absent from ordinary MTDLL builds. */
MTDLL_API MTSTATUS
MtpRunLoaderTests(
    void
);

#endif /* MATANELOS_USERMODE_LOADER_TEST_H */
