#ifndef MATANELOS_USERMODE_LOADER_TEST_H
#define MATANELOS_USERMODE_LOADER_TEST_H

#include "../../shared/include/mtapi.h"
#include "../../shared/include/mtstatus.h"

/* Test-only process exit statuses consumed by the kernel loader controller. */
#define MT_LOADER_TEST_LOAD_FAILED          ((MTSTATUS)0xCF200001L)
#define MT_LOADER_TEST_ENTRY_STATE          ((MTSTATUS)0xCF200002L)
#define MT_LOADER_TEST_REBASE               ((MTSTATUS)0xCF200003L)
#define MT_LOADER_TEST_EXPORT               ((MTSTATUS)0xCF200004L)
#define MT_LOADER_TEST_IMPORT_RELOCATION    ((MTSTATUS)0xCF200005L)
#define MT_LOADER_TEST_DUPLICATE_ENTRY      ((MTSTATUS)0xCF200006L)
#define MT_LOADER_TEST_DUPLICATE_REFERENCE  ((MTSTATUS)0xCF200007L)
#define MT_LOADER_TEST_ATTACH_REPEAT        ((MTSTATUS)0xCF200008L)
#define MT_LOADER_TEST_REJECT_STATUS        ((MTSTATUS)0xCF200009L)
#define MT_LOADER_TEST_REJECT_OUTPUT        ((MTSTATUS)0xCF20000AL)
#define MT_LOADER_TEST_REJECT_ROLLBACK      ((MTSTATUS)0xCF20000BL)
#define MT_LOADER_TEST_LAST_STATUS          ((MTSTATUS)0xCF20000CL)
#define MT_LOADER_TEST_LAST_ERROR           ((MTSTATUS)0xCF20000DL)
#define MT_LOADER_TEST_MODULE_HANDLE        ((MTSTATUS)0xCF20000EL)
#define MT_LOADER_TEST_MISSING_MODULE       ((MTSTATUS)0xCF20000FL)
#define MT_LOADER_TEST_MISSING_EXPORT       ((MTSTATUS)0xCF200010L)
#define MT_LOADER_TEST_INVALID_PARAMETER    ((MTSTATUS)0xCF200011L)
#define MT_LOADER_TEST_UNLOAD_REFERENCE     ((MTSTATUS)0xCF200012L)
#define MT_LOADER_TEST_DETACH               ((MTSTATUS)0xCF200013L)
#define MT_LOADER_TEST_UNLOAD_REMOVAL       ((MTSTATUS)0xCF200014L)
#define MT_LOADER_TEST_RELOAD               ((MTSTATUS)0xCF200015L)
#define MT_LOADER_TEST_PINNED               ((MTSTATUS)0xCF200016L)
#define MT_LOADER_TEST_CONCURRENT           ((MTSTATUS)0xCF200018L)
#define MT_LOADER_TEST_FREE_STATUS          ((MTSTATUS)0xCF200019L)
#define MT_LOADER_TEST_NO_ENTRY_LOAD        ((MTSTATUS)0xCF20001AL)
#define MT_LOADER_TEST_NO_ENTRY_STATE       ((MTSTATUS)0xCF20001BL)
#define MT_LOADER_TEST_NO_ENTRY_EXPORT      ((MTSTATUS)0xCF20001CL)
#define MT_LOADER_TEST_NO_ENTRY_FREE        ((MTSTATUS)0xCF20001DL)
#define MT_LOADER_TEST_NO_ENTRY_REMOVAL     ((MTSTATUS)0xCF20001EL)
#define MT_LOADER_TEST_DEPENDENCY_REFERENCE ((MTSTATUS)0xCF20001FL)
#define MT_LOADER_TEST_PROCESS_PROTECTION   ((MTSTATUS)0xCF200020L)
#define MT_LOADER_TEST_MTDLL_PROTECTION     ((MTSTATUS)0xCF200021L)
#define MT_LOADER_TEST_DLL_PROTECTION       ((MTSTATUS)0xCF200022L)

/* Test-only MTDLL entrypoint. It is absent from ordinary MTDLL builds. */
MTDLL_API MTSTATUS
MtpRunLoaderTests(
    void
);

#endif /* MATANELOS_USERMODE_LOADER_TEST_H */
