#ifndef MATANELOS_USERMODE_PROCESS_TEST_H
#define MATANELOS_USERMODE_PROCESS_TEST_H

#include "../../shared/include/mtstatus.h"

/* Test-only process exit statuses consumed by the kernel process controller. */
#define MT_PROCESS_TEST_CREATE                 ((MTSTATUS)0xCF400001L)
#define MT_PROCESS_TEST_OUTPUT                 ((MTSTATUS)0xCF400002L)
#define MT_PROCESS_TEST_THREAD_WAIT            ((MTSTATUS)0xCF400003L)
#define MT_PROCESS_TEST_PROCESS_WAIT           ((MTSTATUS)0xCF400004L)
#define MT_PROCESS_TEST_THREAD_QUERY           ((MTSTATUS)0xCF400005L)
#define MT_PROCESS_TEST_PROCESS_QUERY          ((MTSTATUS)0xCF400006L)
#define MT_PROCESS_TEST_THREAD_CLOSE           ((MTSTATUS)0xCF400007L)
#define MT_PROCESS_TEST_PROCESS_CLOSE          ((MTSTATUS)0xCF400008L)
#define MT_PROCESS_TEST_MISSING_IMAGE          ((MTSTATUS)0xCF400009L)
#define MT_PROCESS_TEST_MISSING_OUTPUT         ((MTSTATUS)0xCF40000AL)
#define MT_PROCESS_TEST_BAD_ENVIRONMENT        ((MTSTATUS)0xCF40000BL)
#define MT_PROCESS_TEST_BAD_ENVIRONMENT_OUTPUT ((MTSTATUS)0xCF40000CL)
#define MT_PROCESS_TEST_WORKER_CREATE          ((MTSTATUS)0xCF40000DL)
#define MT_PROCESS_TEST_WORKER_WAIT            ((MTSTATUS)0xCF40000EL)
#define MT_PROCESS_TEST_WORKER_QUERY           ((MTSTATUS)0xCF40000FL)
#define MT_PROCESS_TEST_WORKER_CLOSE           ((MTSTATUS)0xCF400010L)
#define MT_PROCESS_TEST_CONCURRENT_CREATE      ((MTSTATUS)0xCF400011L)
#define MT_PROCESS_TEST_CHILD_ARGUMENTS        ((MTSTATUS)0xCF400012L)
#define MT_PROCESS_TEST_CHILD_PARAMETERS       ((MTSTATUS)0xCF400013L)
#define MT_PROCESS_TEST_CHILD_ENVIRONMENT      ((MTSTATUS)0xCF400014L)
#define MT_PROCESS_TEST_NATIVE_PARAMETER_PTR    ((MTSTATUS)0xCF400015L)
#define MT_PROCESS_TEST_NATIVE_OUTPUT_PTR       ((MTSTATUS)0xCF400016L)
#define MT_PROCESS_TEST_NATIVE_IMAGE_PTR        ((MTSTATUS)0xCF400017L)
#define MT_PROCESS_TEST_NATIVE_ALIGNMENT        ((MTSTATUS)0xCF400018L)
#define MT_PROCESS_TEST_READONLY_OUTPUT         ((MTSTATUS)0xCF400019L)
#define MT_PROCESS_TEST_INVALID_IMAGE           ((MTSTATUS)0xCF40001AL)
#define MT_PROCESS_TEST_INVALID_IMAGE_OUTPUT    ((MTSTATUS)0xCF40001BL)
#define MT_PROCESS_TEST_ORPHAN_CREATE           ((MTSTATUS)0xCF40001CL)

#endif /* MATANELOS_USERMODE_PROCESS_TEST_H */
